### ISSUE TITLE
the testing page returns a 404

### ISSUE THREAD

**Issue by charlesfrye** [TeddyFrye/odin-recipes#1]
Reproduction: Go to this link (https://teddyfrye.github.io/odin-recipes/testingpage.html). I found it from the main page (https://teddyfrye.github.io/odin-recipes/) in the list at the bottom.

Expected behavior: links on the main page are all to published pages.

**Comment by Sally-Frye** [comment]
Testing and font page links were removed from home page ([https://teddyfrye.github.io/odin-recipes/index.html](https://teddyfrye.github.io/odin-recipes/index.html)).
They were used for HTML & CSS practice and hold no practical use in the website.

New Status: Only relevant and published pages are available on website.
